M48
; DRILL file {KiCad 9.0.4} date 2026-02-09T19:22:58+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-09T19:22:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X150.0Y-40.0
X150.0Y-110.0
X220.0Y-40.0
X220.0Y-110.0
M30
